/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppRouteImport } from './pages/_app'
import { Route as AuthLoginRouteImport } from './pages/auth/login'

const AppIndexLazyRouteImport = createFileRoute('/_app/')()
const AppDailyActivityIndexLazyRouteImport = createFileRoute(
  '/_app/daily-activity/',
)()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexLazyRoute = AppIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/index.lazy').then((d) => d.Route))
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDailyActivityIndexLazyRoute =
  AppDailyActivityIndexLazyRouteImport.update({
    id: '/daily-activity/',
    path: '/daily-activity/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./pages/_app/daily-activity/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexLazyRoute
  '/daily-activity': typeof AppDailyActivityIndexLazyRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexLazyRoute
  '/daily-activity': typeof AppDailyActivityIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexLazyRoute
  '/_app/daily-activity/': typeof AppDailyActivityIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth/login' | '/' | '/daily-activity'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/' | '/daily-activity'
  id: '__root__' | '/_app' | '/auth/login' | '/_app/' | '/_app/daily-activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/daily-activity/': {
      id: '/_app/daily-activity/'
      path: '/daily-activity'
      fullPath: '/daily-activity'
      preLoaderRoute: typeof AppDailyActivityIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexLazyRoute: typeof AppIndexLazyRoute
  AppDailyActivityIndexLazyRoute: typeof AppDailyActivityIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexLazyRoute: AppIndexLazyRoute,
  AppDailyActivityIndexLazyRoute: AppDailyActivityIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
